# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c76f33ac33b58bc9543ef7d0d1c1c19e8caa84a9001534e100523d63d7559dd681a6d198ff0ae6ec0c9fb490ae8c8c85c71d61d6a11609728b0a170f03ef3910

test:
  secret_key_base: 2a0d37f473eeb846cb4d67598e57bb1c1ef7830cb306829a34d55b902a12f2304055f979d9f2ef9bd49ba7a13b178f6e8d1cb952bcfdbd3fe501510ffb5d0e6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
